import 'package:flutter/widgets.dart';
import 'package:meta/meta.dart';

import 'kulinerdata.dart';

KulinerList kebudayaanList = KulinerList(
  kulinerItems: [
    ItemKulinerData(
      title: "Wayang Topeng Malang",
      urlImage: "https://blogkulo.com/wp-content/uploads/2018/06/Wayang-Topeng-Malang.jpg",
      address: "Kebudayaan Kota Malang",
      detail: "Wayang Topeng Malangan merupakan tradisi budaya dan religiusitas masyarakat Jawa semenjak Kerajaan Kanjuruhan yang dipimpin oleh Raja Gajayana semasa abad ke 8 M. Ini bisa penulis tafsirkan tentang fungsi Candi Badut (arti badut = tontonan) ini menunjukan bahwa saat itu candi berfungsi untuk tontonan “pendidikan yang disampaikan oleh Petinggi / Raja”. Sedangkan Raja Gajayana ini juga mahir menarikan tarian Topeng. Coba anda cermati dari bentuk bangunan candi.   Di Buku Henri Supriyanto, dituliskan Wayang Topeng Malangan mengikuti pola berfikir India, karena sastra yang dominan adalah sastra India. Jadi cerita Dewata, cerita pertapaan, kesaktian, kahyangan, lalu kematian itu menjadi muksa. Sehingga sebutan-sebutannya menjadi Bhatara Agung. Jadi itu peninggalan leluhur kita, sewaktu leluhur kita masih menganut agama Hindu Jawa, yang orientasinya masih India murni. Termasuk wayang topeng juga mengambil cerita cerita dari India, seperti kisah kisah Mahabarata dan Ramayana Dari keterangan diatas bisa diperkuat oleh Almarhum Karimun Bahwa “Kesenian Topeng tidak diperuntukkan acara acara kesenian seperti sekarang ini. Topeng waktu itu yang terbuat dari batu adalah bagian dari acara persembahyangan. Barulah pada masa Raja Erlangga, topeng dikontruksi menjadi kesenian tari. Topeng digunakan menari waktu itu untuk mendukung fleksibilitas si penari. Sebab waktu itu sulit untuk mendapatkan riasan (make up), untuk mempermudah riasan, maka para penari tinggal mengenakan topeng di mukanya”aat kekuasaan Kertanegara di Singasari, wayang topeng ceritanya digantikan dengan cerita cerita Panji. Hal ini dapat dipahami ketika Kertanagera waktu itu menginginkan Singasari menjadi kekuasaan yang sangat besar ditanah Jawa. Panji yang didalamnya mengisahkan kepahlawanan dan kebesaran kesatria kesatria Jawa, terutama masa Jenggala dan Kediri. Cerita Panji dimunculkan sebagai identitas kebesaran raja raja yang pernah berkuasa ditanah Jawa. Cerita cerita Panji yang direkonstruksi oleh Singasari adalah suatu kebutuhan untuk membangun legitimasi kekuasaan Singasari yang mulai berkembang. Wayang Topeng ini dipakai media komunikasi antara kawulo dan gusti, antara raja dan rakyatnya. Kemampuan untuk menyerap segala sesuatunya dan membumikan dalam nilai kejawaan juga banyak terjadi tatkala Islam dan Jawa mulai bergumul dalam konteks wayang topeng."
    ),
    ItemKulinerData(
      title: "Kerajaan Singasari",
      urlImage: "https://i0.wp.com/www.romadecade.org/wp-content/uploads/2018/09/kerajaan-singasari.jpg?fit=739%2C502&ssl=1",
      address: "Kebudayaan Kota Malang",
      detail: "Kerajaan Singasari – Tahukah Anda Tentang Kerajaan Singasari? Kerajaan Singasari merupakan Kerajaan yang berada di Jawa Timur tahun 1222 dan didirikan oleh Ken Arok. Diperkirakan lokasi Kerajaan ini berada di daerah Singasari, Malang. Nama Kerajaan yang sebenarnya adalah Kerajaan Tumapel dan beribukota di Kutaraja. Awalnya Kerajaan Tumapel merupakan sebuah daerah bawahan Kerajaan Kadiri dan waktu itu Tunggul Ametung menjabat sebagai akuwu atau setara camat. Beliau dibunuh dengan cara ditipu oleh pengawalnya sendiri yang bernama Ken Arok yang kemudian menjabat sebagai akuwu baru. Kerajaan ini pernah berjaya pada masa kepemimpinan Kertanagara yang sekaligus menjadi raja terbesar dalam sejarah Kerajaan. Beliau mengirim pasukan Ekspedisi Pamalayu untuk membuat Sumatera sebagai benteng pertahanan. Kemudian pada tahun 1284, beliau juga mengadakan ekspedisi untuk menaklukkan Bali. Runtuhnya Kerajaan ini adalah akibat dari sibuknya mengirim angkatan perang ke luar Jawa serta pemberontakan Jayakatwang dan berhasil membunuh Raja Kertanegara. Jayakatwang kemudian membangun ibukota di Kadiri atau yang sekarang disebut Kediri. Peninggalan Kerajaan Singasari: 1. Candi Jago 2. Candi Singasari 3. Arca Dwarapala 4. Candi Sumberawan 5. Candi Jawi 6. Candi Kidal 7. Prasasti Singasari 8. Prasasti Manjusri 9. Prasasti Wurare 10. Prasasti Mula Malurung"
    ),
    ItemKulinerData(
      title: "Tari Bedayan Malang",
      urlImage: "http://1.bp.blogspot.com/-txI7WEsX7ts/VCDNa7ZF9_I/AAAAAAAAADg/Up5qXyz-gC8/s1600/bedayan.jpg",
      address: "Kebudayaan Kota Malang",
      detail: "Tari adalah salah satu cabang seni yang mengutamakan gerak tubuh. Gerak tubuh ini disesuaikan dengan irama musik yang digunakan. Penggunaan musik ini dimaksudkan agar para penari dapat mengatur serta mengingat gerakan. Selain itu, alunan pengiring ini juga ditujukan untuk memperkuat maksud tarian yang disampaikan. Tarian tradisional yang menjadi khas suatu daerah pun memiliki maksud dan waktu pelaksanaan tertentu. Butuh waktu-waktu khusus untuk dapat menampilkan tarian tersebut. Sebab, ada tarian yang memang ditampilkan dalam serangkaian upacara adat. Sehingga, beberapa dari tarian tradisional masih dianggap sakral. Tidak hanya untuk upacara adat, banyak juga tarian yang dimaksudkan untuk penyamputan para tamu istimewa. Salah satunya yaitu tari Bedayan. Tari Bedayan merupakan tarian yang berasal dari Malang. Tarian ini biasa dibawakan oleh sembilan penari. Tidak seperti tarian yang lainnya, masing-masing penari memiliki nama tersendiri. Nama-nama tersebut adalah Apit ngajeng, Apit Meneng, Apit Wingking, Batak, Buncit, Dada, Endel, Endel Weton, dan Gulu. Nama-nama yang berbeda tersebut menunjukkan peran yang berbeda pula. Meskipun perannya terlihat berbeda, namun bukan berarti bahwa para penari berjalan sendiri atau tidak sinkron satu sama lain. Penari-penari tersebut membawakan tarian sesuai peran yang dibawakan. Dimana seluruhnya menghasilkan suatu keutuhan makna yang sesuai tujuan tari ini. Sebagai tarian untuk menyambut para tamu, tarian ini memiliki makna tentang keterbukaan masyarakat dalam menerima tamu. Keterbukaan ini mengartikan bahwa masyarakat menghargai dan menghormati hadirnya tamu. Sebab, tamu tidak hanya bermanfaat untuk menjaga tali silaturahmi tetapi juga untuk mendapatkan keberkahan. Sebab, masyarakat banyak meyakini bahwa tamu adalah orang yang diperlakukan istimewa bak raja. Dimana didalamnya pasti akan membawa keberkahan. Meskipun para penari membawakannya dengan luwes dan gemulai, namun tarian ini dibawakan dengan sederhana dan lugas. Sehingga makna yang tersampaikan dapat mengena ke penikmatnya."
    ),
    ItemKulinerData(
      title: "Boso Walikan",
      urlImage: "https://assets-a2.kompasiana.com/items/album/2018/05/05/kera-ngalam-5aeda3e5bde5757f646a2bc2.jpg?t=o&v=760",
      address: "Kebudayaan Kota Malang",
      detail: "Berdasar buku Malang Tempoe Doeloe dari Dukut Imam Widodo, bahasa ini disebut diciptakan oleh kelompok Gerilya Rakyat Kota yang berjuang di wilayah sekitar Malang. Bahasa ini mulai berkembang sekitar tahun 1949 pada masa Clash II perang kemerdekaan. Banyaknya mata-mata dari pihak Belanda pada masa itu membuat para pejuang memikirkan cara tertentu untuk mengirim pesan yaitu dengan boso walikan. Pada masa perang, bahasa ini digunakan sebagai sebuah kode untuk mengirim pesan pada sesama pejuang republik. Selain untuk menjamin kerahasiaan dan sebagai cara komunikasi, bahasa ini juga dianggap sebagai pengenal identitas antara kawan dan lawan. Disebutkan oleh Dukut Imam Widodo bahwa ide untuk membalik bahasa ini pertama kali dicetuskan oleh seorang pejuang yang bernama Suyudi Raharno. Agar tidak mudah dipecahkan, bahasa ini tidak menggunakan aturan tata bahasa yang umum dan baku. Selain itu, bahasa ini juga memiliki beberapa kosa kata yang khas sehingga cukup efektif sebagai sebuah kode rahasia. Pada akhirnya bahasa ini memang terbukti ampuh untuk mengirim pesan sekaligus mengetahui mata-mata yang menyusup pada kubu tentara republik.  Apa Sih Yang Menarik Dari Boso Walikan Malang ? 1. Sebagai Penunjuk Identitas 2. Bahasa Tingkat Tinggi 3. Orang yang menggunakan bahasa ini rata-rata orang cerdas 4. Bahasa yang ruwet tapi asik 5. Contoh Beberapa Boso Walikan "
    ),
    ItemKulinerData(
      title: "Tari Grebeg Wiratama",
      urlImage: "http://brangwetan.files.wordpress.com/2008/11/karimun-topeng.jpg",
      address: "Kebudayaan Kota Malang",
      detail: "Tari ini menggambarkan semangat dan keperwiraan prajurit yang berangkat perang, disamping itu sifat manusia yang terkadang humoris dan “ngglece” tergambar pula dalam tarian ini.   Kesenian: Tari Topeng Malangan Kesenian Tari Topeng Malangan ini adalah hasil dari perpaduan antara budaya Jawa Tengahan, Jawa Kulonan dan Jawa Timuran (Blambangan dan Osing), sehingga gerakan dari Tari Topeng Malangan ini mengandung unsur kekayaan dinamis dan musik dari etnik Jawa, Madura dan Bali. Tari Topeng Malangan ini merupakan perlambang bagi sifat manusia, karenanya banyak model topeng yang menggambarkan situasi yang berbeda, menangis, tertawa, sedih, malu dan sebagainya "
    ),
  ]
);
